name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: air
    timeout-minutes: 1

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
